import Foundation

/// Token consumption from Claude Code sessions (last 24 h).
struct CavemanStats: Equatable {
    // MARK: - Token volumes
    /// Fresh tokens sent to the model (not served from cache)
    let inputTokens: Int
    /// Tokens written to the prompt cache
    let cacheCreationTokens: Int
    /// Tokens served from the prompt cache
    let cacheReadTokens: Int
    /// Tokens generated by the model
    let outputTokens: Int

    // MARK: - Activity
    /// Number of JSONL session files read
    let sessionCount: Int
    /// Number of individual assistant turns parsed
    let messageCount: Int
    /// Number of tool_use content blocks across all sessions
    let toolCallCount: Int
    /// Distinct project directories touched in the lookback window
    let activeProjects: Int

    // MARK: - Model breakdown (model ID → total tokens processed)
    let modelUsage: [String: Int]

    // MARK: - Computed

    var cachedTokens: Int { cacheCreationTokens + cacheReadTokens }
    var totalInputTokens: Int { inputTokens + cachedTokens }

    /// output / totalInput — lower = terser responses
    var compressionRatio: Double {
        guard totalInputTokens > 0 else { return 0 }
        return Double(outputTokens) / Double(totalInputTokens)
    }

    /// Fraction of cached tokens served from cache vs. newly written
    var cacheHitRate: Double {
        guard cachedTokens > 0 else { return 0 }
        return Double(cacheReadTokens) / Double(cachedTokens)
    }

    var avgTokensPerSession: Int {
        guard sessionCount > 0 else { return 0 }
        return totalInputTokens / sessionCount
    }

    /// Model ID that consumed the most tokens in the window
    var dominantModel: String? {
        modelUsage.max(by: { $0.value < $1.value })?.key
    }

    /// Estimated cost in USD using dominant model's pricing.
    var estimatedCostUSD: Double {
        let p = CavemanPricing.pricing(for: dominantModel)
        let M = 1_000_000.0
        return Double(inputTokens)         / M * p.inputPerMTok
             + Double(cacheCreationTokens) / M * p.cacheWritePerMTok
             + Double(cacheReadTokens)     / M * p.cacheReadPerMTok
             + Double(outputTokens)        / M * p.outputPerMTok
    }
}

// MARK: - Pricing table

struct CavemanPricing {
    let inputPerMTok: Double
    let cacheWritePerMTok: Double
    let cacheReadPerMTok: Double
    let outputPerMTok: Double

    static func pricing(for modelID: String?) -> CavemanPricing {
        guard let id = modelID?.lowercased() else { return .sonnet }
        if id.contains("haiku") { return .haiku }
        if id.contains("opus")  { return .opus }
        return .sonnet
    }

    // Per million tokens — Anthropic list pricing May 2025
    static let haiku  = CavemanPricing(inputPerMTok:  0.80, cacheWritePerMTok:  1.00, cacheReadPerMTok: 0.08, outputPerMTok:  4.00)
    static let sonnet = CavemanPricing(inputPerMTok:  3.00, cacheWritePerMTok:  3.75, cacheReadPerMTok: 0.30, outputPerMTok: 15.00)
    static let opus   = CavemanPricing(inputPerMTok: 15.00, cacheWritePerMTok: 18.75, cacheReadPerMTok: 1.50, outputPerMTok: 75.00)
}
