import Foundation

/// Token consumption from Claude Code sessions (last 24 h).
///
/// "Savings" cannot be computed without a no-Caveman baseline, so we expose
/// raw volumes. The output/input ratio is a rough compression proxy.
struct CavemanStats: Equatable {
    /// New tokens sent to the model (not cached)
    let inputTokens: Int
    /// Tokens served from cache (cache_read + cache_creation combined)
    let cachedTokens: Int
    /// Tokens generated by the model
    let outputTokens: Int
    /// Number of JSONL session files read
    let sessionCount: Int

    /// True input volume (what was billed) = inputTokens + cachedTokens
    var totalInputTokens: Int { inputTokens + cachedTokens }

    /// output / totalInput — lower = terser responses (proxy for Caveman compression)
    var compressionRatio: Double {
        guard totalInputTokens > 0 else { return 0 }
        return Double(outputTokens) / Double(totalInputTokens)
    }
}
